version: '3'
services:
  php-fpm:
    working_dir: /var/www
    container_name: php-fpm
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    restart: "no"

  nginx:
    working_dir: /var/www
    container_name: nginx
    image: nginx:latest
    volumes:
      - ${APPLICATION}:/var/www
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    ports:
      - "${CONFIG_NGINX_HTTP_PORT}:80"
      - "${CONFIG_NGINX_HTTPS_PORT}:443"
    links:
      - php-fpm
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "${CONFIG_MARIADB_PORT}:3306"
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql